name: pipeline

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  test:
    uses: guilhermelinosp/ci-templates/.github/workflows/dotnet-build.yml@main
    with:
      runner: ubuntu-latest
      version: "0.0.0"

  release:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    uses: guilhermelinosp/ci-templates/.github/workflows/release.yml@main
    secrets: inherit
    with:
      runner: ubuntu-latest

  publish:
    if: github.ref == 'refs/heads/main'
    needs: [release]
    uses: guilhermelinosp/ci-templates/.github/workflows/dotnet-push.yml@main
    secrets: inherit
    with:
      runner: ubuntu-latest
      version: ${{ needs.release.outputs.version }}
